### ISSUE TITLE
[🐛 bug] 代码显示为 `[object Object]`

### ISSUE THREAD

**Issue by XcantloadX** [ha0z1/New-Bing-Anywhere#145]
用谷歌搜索 `c# datagridview paste from excel` 时出现的，不太清楚是不是插件的问题
![image](https://github.com/haozi/New-Bing-Anywhere/assets/25605245/8cef2389-7e85-47ec-914a-a956d394927d)

<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en-GB, en-US, zh-CN, en, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: c# datagridview paste from excel

conversation: https://sydney.bing.com/sydney/GetConversation?conversationId=51D%7CBingProd%7CA7CEFA4F82B1D298BAE40D5D12508FC6CCCFF835F4571F410C56E255A0111352&source=cib&participantId=18A5DDBFE1216DBC33FACEFBE0206CD4&conversationSignature=fv1Rv1J5Ig0griI0nQuy2JvpbvHhPaPH3TkDlAT%2F68A%3D</pre>

**Comment by haozi** [comment]
yes, it's my bug, thanks, i will fix it next version
