### ISSUE TITLE
用google搜索侧边脸new bing anywhere显示Cannot retrieve user status

### ISSUE THREAD

**Issue by ggfggggjqd** [ha0z1/New-Bing-Anywhere#166]
Error: There seem to be some errors :Cannot retrieve user status.

You can try the following methods to fix them:

Make sure you have successfully logged into your Microsoft account on [Bing.com](https://www.bing.com/). And ensure that the MS account is not banned (able to chat successfully on [Bing-chat](https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx)).
If you are using browsers like Brave, please make sure you have allowed third-party cookies for the domain `www.google.com.hk`.
There might be a Network Error, if you are from a country or region that does not support the New Bing Chat. You may need to configure a network proxy correctly. Refer to [<Configure the Network Proxy>](https://github.com/haozi/New-Bing-Anywhere/issues/8) for more information.
Click the force refresh button in the top right corner and try again.

**Comment by haozi** [comment]
Try to follow #8 and give more information
