### ISSUE TITLE
您現在可以存取全新的 Bing，這是您的 AI 支援 Copilot 網頁版。

### ISSUE THREAD

**Issue by hwoarangkang** [ha0z1/New-Bing-Anywhere#168]
一樣跳出需要下載Edge才能使用的頁面，無法正常使用！
![iShot_2023-08-09_08 03 36](https://github.com/haozi/New-Bing-Anywhere/assets/84637421/16d43800-5da2-44c1-a822-c8759d9d677e)

<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-TW
AcceptLangs: zh-TW, zh, en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
什么浏览器，说清楚
