### ISSUE TITLE
提示：error on line 1 at column 1: Document is empty

### ISSUE THREAD

**Issue by smillsion** [ha0z1/New-Bing-Anywhere#169]
**点击提示，是微软的提示，还是程序错误，或者是我配置错误？**
![image](https://github.com/haozi/New-Bing-Anywhere/assets/30746188/57ff2f33-852d-46d3-84a6-72e535321756)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/30746188/ac99fae7-af8c-479b-86bd-dff18cce4926)
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en-US, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
</pre>

**Comment by haozi** [comment]
禁用插件后呢？

**Comment by smillsion** [comment]
> 禁用插件后呢？

刚又试了下。又可以了。

![image](https://github.com/haozi/New-Bing-Anywhere/assets/30746188/44d6fb73-d4e3-4bf9-bca0-7299303f1f0a)

**Comment by XiaoZiShan** [comment]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/33439399/a219c574-9728-41f8-b180-14e3f60303b2)

The plug-in is disabled, but the problem still occurs.

**Comment by XiaoZiShan** [comment]
> ![image](https://user-images.githubusercontent.com/33439399/260311343-a219c574-9728-41f8-b180-14e3f60303b2.png)
> 
> The plug-in is disabled, but the problem still occurs.

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/33439399/f2bd5982-0119-4a7c-9c52-232a13323c76)

I used a vpn in Japan

**Comment by XiaoZiShan** [comment]
@haozi I can trace this issue, please reopen the issue
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/33439399/911fd33a-33ef-4979-b384-d1ee99d9bfee)

**Comment by XiaoZiShan** [comment]
I repeatedly opened the plugin and the problem was solved, but I often encountered it. soon now met again

**Comment by haozi** [comment]
which browser？ Chrome？
have you tried disable all other extensions and change another IP？

**Comment by XiaoZiShan** [comment]
> which browser？ Chrome？ have you tried disable all other extensions and change another IP？

Yes, Chrome, sure, i try to disable and change IP, see nothing

**Comment by XiaoZiShan** [comment]
Now it's fine again, I encounter it every day, and if it works out, I'll share my experience.

**Comment by XiaoZiShan** [comment]
I rarely trigger this page after using google as my primary search engine.
