### ISSUE TITLE
I can't use

### ISSUE THREAD

**Issue by mingqing702** [ha0z1/New-Bing-Anywhere#173]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 京津冀多部门投入救援力量
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible.
</pre>

**Comment by haozi** [comment]
see #8
