### ISSUE TITLE
希望添加华为浏览器（PC）支持

### ISSUE THREAD

**Issue by Looong01** [ha0z1/New-Bing-Anywhere#174]
希望添加华为浏览器（PC）支持
https://consumer.huawei.com/cn/mobileservices/browser/

**Comment by haozi** [comment]
mobile？

**Comment by Looong01** [comment]
> mobile？

No, it is Windows x64 version of Huawei Browser.

**Comment by haozi** [comment]
It looks to be working  well.

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/d34eb754-20f1-4dcd-be4a-ded6e5945f46)
