### ISSUE TITLE
firefox下访问专制提示打开/下载edge

### ISSUE THREAD

**Issue by seeyisee** [ha0z1/New-Bing-Anywhere#175]
bing主页能看到chat图标，点击有如题提示。

<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Lang: zh-CN
AcceptLangs: zh-CN, zh, zh-TW, zh-HK, en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
请好好说话，表达问题，中文*英语都可以

**Comment by seeyisee** [comment]
哪不好好说话了

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/8

**Comment by seeyisee** [comment]
不符合FAQ里的情况，之前一直可以用改header的方式访问，最近几周才不行，怀疑微软进行了进一步的区分鉴定

**Comment by seeyisee** [comment]
我的设置问题，好了

**Comment by haozi** [comment]
Please provide some screenshots and detailed reproduction steps, and do not discuss any political topics.
