### ISSUE TITLE
Error: There seem to be some errors :Cannot retrieve user status.

### ISSUE THREAD

**Issue by widiru83** [ha0z1/New-Bing-Anywhere#178]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, ar-JO, ar, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 8cx gen 2 vs 7c gen 2
stack: Error: Cannot retrieve user status.
</pre>

**Comment by haozi** [comment]
login you MS account, ensure can chat success on Bing.com

see #8
