### ISSUE TITLE
submit

### ISSUE THREAD

**Issue by MILESMAKMAK** [ha0z1/New-Bing-Anywhere#190]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 央媒：并非所有人都适合体制内工作
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible.
</pre>

**Comment by haozi** [comment]
Bing 帐号没登录
