### ISSUE TITLE
issus

### ISSUE THREAD

**Issue by out2null** [ha0z1/New-Bing-Anywhere#192]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en-CN, en, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 李香兰
stack: Error: Cannot retrieve user status.
</pre>

**Comment by haozi** [comment]
#8

**Comment by out2null** [comment]
thanks
