### ISSUE TITLE
无法用bing了

### ISSUE THREAD

**Issue by shipand** [ha0z1/New-Bing-Anywhere#193]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54
Lang: zh-CN
AcceptLangs: zh-CN, en-US, zh-HK, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
一句话 issue，让我猜迷吗？

**Comment by shipand** [comment]
地址栏搜索时，变成这样的
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/51933636/3ed06f48-324d-4c59-8dbd-dc2086a913af)

**Comment by shipand** [comment]
或者 这样
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/51933636/e9756d40-d137-4e6f-bd47-98a07c583eb7)

**Comment by haozi** [comment]
开启 DRF(Dangerous Request Forgery) 选项或更换梯子再试

**Comment by shipand** [comment]
开DRF不行，要请缓存吗

**Comment by haozi** [comment]
你这个应该是 IP 被 ban 了
