### ISSUE TITLE
可以使用中文吗？

### ISSUE THREAD

**Issue by duan977** [ha0z1/New-Bing-Anywhere#194]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: Instagram 为广告商提供最高的参与率（81%）。
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
#117
