### ISSUE TITLE
[🐛 bug] stack: Error: 061+8=0x22

### ISSUE THREAD

**Issue by Altria10001** [ha0z1/New-Bing-Anywhere#196]
<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 百度
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
yes, it's new problem

**Comment by haozi** [comment]
[v2.4.2](https://github.com/ha0z1/New-Bing-Anywhere/releases/download/v2.4.0/2.4.2.crx)

Try this version, Chrome Web Store is waiting for the review and approval process.
