### ISSUE TITLE
Clicking on old chats in Recent Activity do not open them

### ISSUE THREAD

**Issue by ADTC** [ha0z1/New-Bing-Anywhere#197]
It looks like if I click on any old chat in Recent Activity section, it doesn't do anything. I expected the full chat on the left or somewhere. I can however use the menu to export them to PDF, text, etc..

Not sure if this is a Bing bug though. I don't have Edge browser right now to test.

I'm using Firefox 116.0.3

**Comment by haozi** [comment]
It wasn't me, Microsoft did it.

**Comment by ADTC** [comment]
@haozi  I just installed Edge on my system (macOS) to test something unrelated. Then I also tested this. It works fine on Edge, but not on Firefox. Could it be related to the extension?

**Comment by haozi** [comment]
> @haozi I just installed Edge on my system (macOS) to test something unrelated. Then I also tested this. It works fine on Edge, but not on Firefox. Could it be related to the extension?
 
https://github.com/ha0z1/New-Bing-Anywhere/issues/226#issuecomment-1720409901 😭

**Comment by ADTC** [comment]
I would think this should be re-opened btw, since it works fine on a clean Edge installation without any extension (including this one).

The other thing that works fine in Edge but not in Firefox is the ability to switch between chat and search by scrolling up and down (although it's really annoying and I actually don't want it working in Firefox).
