### ISSUE TITLE
It won't work! Everytime it is showing error code 061+8=0x22

### ISSUE THREAD

**Issue by Awesome126** [ha0z1/New-Bing-Anywhere#198]
Every moment I type in Google Search and search for a result, the Bing Chat result popped out by the extension won't show any information I search for, instead of that an error code 061+8=0x22... I can access the Bing, Bing Chat, and can chat joyfully with it through its official entrance. Btw, I am using Google Chrome in which the Bing Chat is just allowed to be use started from yesterday. I wonder what the error code 061+8=0x22 means? maybe it's a connection error, but I can chat with Bing Chat directly, it's the thing! Appreciate your work. I would thank you more with a love gesture if you can sort this problem out. Thanks.

<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: marvellous
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/196

**Comment by haozi** [comment]
update to 2.4.2+ 
https://github.com/ha0z1/New-Bing-Anywhere/issues/196#issuecomment-1700743058
