### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by RADWolves** [ha0z1/New-Bing-Anywhere#200]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/137776739/54e0e0e1-1097-47f2-bccb-c34e386f0df2)

<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188
Lang: en-US
AcceptLangs: en-US, en, hi
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: lod bias unity
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/196
