### ISSUE TITLE
Google搜索无法使用Bing

### ISSUE THREAD

**Issue by quentinck** [ha0z1/New-Bing-Anywhere#201]
点击插件的bing链接可以正常范围，但插件就不显示内容，提示信息如下：
Error: There seem to be some errors :061+8=0x22

You can try the following methods to fix them:

Make sure you have successfully logged into your Microsoft account on [Bing.com](https://www.bing.com/). And ensure that the MS account is not banned (able to chat successfully on [Bing-chat](https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx)).
If you are using browsers like Brave, please make sure you have allowed third-party cookies for the domain `www.google.com`.
There might be a Network Error, if you are from a country or region that does not support the New Bing Chat. You may need to configure a network proxy correctly. Refer to [<Configure the Network Proxy>](https://github.com/ha0z1/New-Bing-Anywhere/issues/8) for more information.
Click the force refresh button in the top right corner and try again.
If it remains unresolved, please  to us, or

<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en, zh-TW, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 12431234
stack: Error: 061+8=0x22
</pre>

**Comment by quentinck** [comment]
前一阵可以用，这两天发现有问题。

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/196

**Comment by quentinck** [comment]
楼主真速度，坐等更新

**Comment by haozi** [comment]
> 楼主真速度，坐等更新

可以手动安装 2.4.2
