### ISSUE TITLE
协议

### ISSUE THREAD

**Issue by liyeszxc** [ha0z1/New-Bing-Anywhere#203]
<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: a beautiful girl
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/196#issuecomment-1700743058
