### ISSUE TITLE
Ability to hide Recent activity chat and maximize chat window

### ISSUE THREAD

**Issue by cyin2000** [ha0z1/New-Bing-Anywhere#206]
Hi,

I use Bing Anywhere everyday and love it.  Would it be possible to be able to hide right pane Recent activity chat and maximize chat window.  I don't care about Recent activity chat.  I would like the maximum space for chat window for the display so that I don't have to scroll down and up for large gpt response.  Thanks for the excellent app !

Charles

<pre>
Version: 2.4.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
It's not me, MS did it.

**Comment by cyin2000** [comment]
Thanks for the reply !
