### ISSUE TITLE
There seem to be some errors :061+8=0x22  You can try the following methods to fix them

### ISSUE THREAD

**Issue by djl91888** [ha0z1/New-Bing-Anywhere#212]
<pre>
Version: 2.4.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 辽宁队签名篮球
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/196#issuecomment-1700743058
