### ISSUE TITLE
無法識圖

### ISSUE THREAD

**Issue by Namarimizu** [ha0z1/New-Bing-Anywhere#214]
其它功能似乎都正常，唯獨發送圖片之後提示三次「分析图像: 隐私模糊会隐藏必应聊天中的人脸」後報錯「上一条消息似乎已中断」，點擊重新發送之後沒有反應🤔

**Comment by haozi** [comment]
<img width="1259" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/969d02bc-ae0d-4989-83fb-f612d18271f3">

試了可以的，嘗試在设置選項裏開啓 DRF(Dangerous Request Forgery) 選項試試？

另外提供一下具體運行環境信息
