### ISSUE TITLE
无法使用,要求登录bing账号,但已经登陆了.

### ISSUE THREAD

**Issue by thomasTAT** [ha0z1/New-Bing-Anywhere#215]
有人一样吗?
奇怪的是是,相同账号,edge beta上,chrome上没问题.

<pre>
Version: 2.4.3 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69
Lang: zh-CN
AcceptLangs: zh-CN, en, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Creative"}
engine: google
query: how are you
stack: Error: The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=
</pre>

**Comment by haozi** [comment]
没有允许第三方 cookie 吧

**Comment by thomasTAT** [comment]
> 

重设了,edge浏览器设置,正常了. 谢谢

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/219
