### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by tinystern** [ha0z1/New-Bing-Anywhere#216]
<pre>
Version: 2.4.3 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 有无相生造句
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by tinystern** [comment]
你好

**Comment by tinystern** [comment]
hi

**Comment by haozi** [comment]
#8
