### ISSUE TITLE
edge浏览器（版本 116.0.1938.76 (正式版本) (64 位)），使用clash可以正常使用bingchat，但在谷歌搜索界面就不行

### ISSUE THREAD

**Issue by 2eggiangli3** [ha0z1/New-Bing-Anywhere#221]
<pre>
前两张图是bing ai界面
</pre>

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/74344317/4b53cda9-ed5c-4617-a1cf-101721362ad9)

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/74344317/4e14dd24-41c3-4bea-92df-b82ffdd265a7)

<pre>
这个是是谷歌界面
</pre>

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/74344317/e12924ec-1762-4c41-af66-a03b25a6fbb5)

<pre>
Version: 2.4.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en-US, en, en-GB
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Precise","X-Forwarded-For":"123.23.12.43"}
engine: google
query: 我正在规划我的9月份的周年纪念日旅行。能帮忙推荐一些距伦敦希思罗机场航程不超过3小时的去处吗？
stack: Error: The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=
</pre>

**Comment by haozi** [comment]
巨硬又升级策略了，升级到 2.4.5 以上版本， chrome 市场还在审核中，可以手动下载 crx 文件，拖动安装

https://github.com/ha0z1/New-Bing-Anywhere/issues/219

**Comment by 2eggiangli3** [comment]
好的bro
