### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 37s** [ha0z1/New-Bing-Anywhere#227]
<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: Dynamic Grained Encoder for Vision Transformers解析
stack: Error: Request is throttled. Please try again later.
</pre>

**Comment by haozi** [comment]
Request is throttled 被限流了，换 IP 和帐号
