### ISSUE TITLE
One moment while we try to connect

### ISSUE THREAD

**Issue by wu-cheng-yang** [ha0z1/New-Bing-Anywhere#228]
all confiurations are following the instructions, but "One moment while we try to connect " today.

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by wu-cheng-yang** [comment]
for the latest google chrom version.

**Comment by wu-cheng-yang** [comment]
<img width="1756" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/140724634/8313c834-05a3-440c-8687-2c2b34094fb5">
<img width="1762" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/140724634/a3b139e7-03fd-4d48-8f7e-c0d3c9772ace">

**Comment by haozi** [comment]
disabled the extension, and retry?

**Comment by wu-cheng-yang** [comment]
> disabled the extension, and retry?

Bad lucky, the same as the before.
disable the extension=====> failed,
reboot chrome and enable the extension =======> failed.

**Comment by haozi** [comment]
Then it's not a problem with my extension. Try changing the MS account and IP.

**Comment by wu-cheng-yang** [comment]
Its failed after changing the MS account.

I Will try to change Ip for a test.Btw, its successful when I viste new bing on My phone by the same newwork(the same IP, the same proxy).

**Comment by haozi** [comment]
If the network and account remain unchanged, what will be the result if you try using Edge?

**Comment by wu-cheng-yang** [comment]
Sorry, I tested just now on Edge with the same account ,but failed.

I should fix the last comment, I failed visit new bing  too on my phone the same as the result in my server.

it seems like that only one way left that Changing my proxy Ip address.

**Comment by wu-cheng-yang** [comment]
It looks like everything goes well without any changing of network and account.
