### ISSUE TITLE
Tried out, didn't work on opera

### ISSUE THREAD

**Issue by ivcr01** [ha0z1/New-Bing-Anywhere#229]
So I tested on other browsers but opera gx in particular isn't working. It just doesn't give the option for Bing AI

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0
Lang: pt-BR
AcceptLangs: pt-BR, pt, en-US, en, de-DE
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
Try this
https://github.com/ha0z1/New-Bing-Anywhere/issues/58
