### ISSUE TITLE
auto transfer into CN for bing web

### ISSUE THREAD

**Issue by suns1232023** [ha0z1/New-Bing-Anywhere#233]
自动跳转bing国内国外，无法直接访问www.bing.com

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8
