### ISSUE TITLE
Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by majq1990** [ha0z1/New-Bing-Anywhere#234]
不知道是否我的服务器被封杀了，github正常， newbing一直封杀。用插件也不行

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en, zh
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8
