### ISSUE TITLE
Aug 26: Microsoft has recently upgraded its policies,We are currently working on resolving this matter. 近期微软升级了策略，会导致部分 Chrome 用户无法正常使用

### ISSUE THREAD

**Issue by haozi** [ha0z1/New-Bing-Anywhere#24]
## 2023/08/26 

Microsoft has recently upgraded its policies, causing some Chrome users to experience issues. We are currently working on resolving this matter.Welcome to create a new issue for feedback (do not reply here).

近期微软升级了策略，导致部分 chrome 用户无法正常使用，正在解决中，欢迎新开 issue 反馈(不要在此跟帖)

## 2023/07/11

Recently, we have added numerous new features and implemented new strategies to counteract Bing's blocking measures.
Due to the addition of support for over 100 independent country-specific domain names for Google, the latest version may prompt permission changes in Chrome. Don't panic; we strictly adhere to the principle of minimal necessary permissions and do not request unnecessary access. The code is open to scrutiny by everyone.

You can also manually install the new preview version to experience the new features and provide us with feedback and suggestions.

https://github.com/haozi/New-Bing-Anywhere/releases

过去的一个月，我们增加了大量新功能和新的策略应对必应的封堵。由于我们增加了对 Google 的100多个独立国别域名的支持，最新版本可能会提示 Chrome 中的权限更改。不要恐慌。我们严格遵守最小必要权限的原则，我们的代码开放供所有人阅读。

**Comment by JAJA-WHB** [comment]
还是不能用啊

**Comment by haozi** [comment]
> 

https://t.me/new_bing_anywhere

**Comment by electrolyte-orb** [comment]
Just wanted to thank you. Open source is one thankless beast.

**Comment by banxian** [comment]
this banner on top will auto hidden without restore 40px top padding on page body.

**Comment by haozi** [comment]
> this banner on top will auto hidden without restore 40px top padding on page body.

Got it. However, it's not matter. Once you have read the notification, you can click the close button, and it will no longer appear
