### ISSUE TITLE
recaptcha mutli times 验证时重复多次

### ISSUE THREAD

**Issue by GOUKI9999** [ha0z1/New-Bing-Anywhere#240]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/11640942/9c0508e4-4594-4b24-b14d-787e1da2e18c)

chrome 最新版本，使用clash及相关自写bing规则，机场ip应该在可以使用 bing的区域（美国）
代理途径为chrome-系统代理-clash接管-规则分流
个人ms账号，中文win11最新版

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/11640942/29b8240a-2756-48e3-98d5-2ecd0e6dd127)

如最上图，间隔一段时间不使用后会要求验证是否真人(recaptcha)，但是部分时候会重复验证多次并反复出现，最多时超过6次且最后会卡住无法通过，部分时候重复3-4次后通过

不太确定是什么原因，目前还没在其他相同或接近的环境下复现

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en-CN, en, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
微软的策略，这背后可是 cloudflare 和 openai，有大量的判断 IP 的方法和经验。多换 IP，可以试试 cloudflare 的 zero trust 或购买独立服务器 ip

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/285
