### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jeffreynet** [ha0z1/New-Bing-Anywhere#249]
当前无法使用此页面www.bing.com 重定向次数过多。
若要解决此问题，请尝试[清除 Cookie] 
ERR_TOO_MANY_REDIRECTS

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
梯子问题

**Comment by jeffreynet** [comment]
解决了，是我多级代理设置问题。谢谢
