### ISSUE TITLE
未重定向，仍无法使用newbing

### ISSUE THREAD

**Issue by guojianrongtj** [ha0z1/New-Bing-Anywhere#255]
edge普通版，使用插件，地址栏显示未重定向，账户区域改为美国，仍无法开启newbing。
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/50268990/1641f210-ae6b-406b-8192-a659e2f43757)

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
Lang: zh-CN
AcceptLangs: zh-CN, en-US
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":true,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by guojianrongtj** [comment]
补充：已经使用魔法上网（cloudflare warp）

**Comment by haozi** [comment]
没翻墙成功
