### ISSUE TITLE
使用 bing 搜索时，google 的 button 定位错误

### ISSUE THREAD

**Issue by curlykay** [ha0z1/New-Bing-Anywhere#256]
<img width="1439" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/35558285/b5329121-b815-4426-84c1-3727f3f34655">

补充信息：
设备：macbook pro 13 2018
浏览器：chrome v117.0.5938.149

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by curlykay** [comment]
没效果，在无痕模式下只使用这个插件也测试了下，同样的问题
<img width="1439" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/35558285/c2d0959a-f46c-4048-bbda-cef1395069dd">

**Comment by haozi** [comment]
电脑分辨率多少？

**Comment by curlykay** [comment]
1440*900
<img width="715" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/35558285/f42941d2-a841-44dd-bc0c-6f996657c5d6">

**Comment by CarryOnHxy** [comment]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/41328326/8f3f8260-4479-45d2-a110-95fa94f0cf65)
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/41328326/d6b728f3-1142-4fec-93f8-9738a4191776)
windows也出现了

**Comment by haozi** [comment]
Upgrade larger than 2.6.0
