### ISSUE TITLE
Add Dark Mode option

### ISSUE THREAD

**Issue by Awadesh365** [ha0z1/New-Bing-Anywhere#261]

**Comment by haozi** [comment]
We have dark mode

**Comment by haozi** [comment]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/8d85c6c3-9c6d-44f5-9615-48a0060c7102)
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/1e8dc99a-dc30-4d4f-98b0-9989b1240fbb)
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/c1588c1b-b286-44f0-965e-73911a96ad7d)

**Comment by Awadesh365** [comment]
Amazing!, Thank You Very much.

**Comment by haozi** [comment]
It will follows the global theme set by the search engine page and does not support individual customization
