### ISSUE TITLE
Calcula el valor correcto para el planteamiento.  En el colegio "Rockero", a 40 de sus 80 estudiantes les gusta la cumbia. En el colegio "Salsero" hay 60 estudiantes y a 45 les gusta la cumbia. En el colegio "Cumbiero" hay 100 estudiantes y a 30 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia?     A)   "Cumbiero"     B)   "Rockero"     C)   "Salsero"     D)    "Cumbiero" y "Rockero"

### ISSUE THREAD

**Issue by sugar35** [ha0z1/New-Bing-Anywhere#263]
<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: es-EC
AcceptLangs: es-419, es
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
Need More Info to Reopen
