### ISSUE TITLE
无法和new bing聊天

### ISSUE THREAD

**Issue by Zhumomo** [ha0z1/New-Bing-Anywhere#265]
可以打开new bing聊天页面，但是发送问题后，就显示‘正常尝试重新连接’
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/36159737/af3e3126-42c4-47bb-952d-c16f937c31f2)

<pre>
Version: 2.4.6 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
梯子问题，试试开启 DRF 开关，如果不行只能换梯子

**Comment by micchi1108** [comment]
你解决了吗？我也遇到了这个问题
