### ISSUE TITLE
用New-Bing-Anywhere插件，在chrome浏览器下，无法更改bing网站的地区为美国。

### ISSUE THREAD

**Issue by captainfrm** [ha0z1/New-Bing-Anywhere#267]
我在chrome浏览器下安装了New-Bing-Anywhere的插件，打开Clash for Windows猫。Clash for Windows猫设置为了美国。
我登录bing网站时发现，我的地址永远是中国，不能更改为美国。
截图如下 。
![bing](https://github.com/ha0z1/New-Bing-Anywhere/assets/148782953/1a409241-cd43-497e-8bb6-38e0358705b0)
这个问题怎么解决？目前看 New-Bing-Anywhere插件不能解决无法使用New bing chatGDP问题。
希望谁能帮帮我？或者告诉我还需要提供什么信息？

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
没翻墙成功啰，bing.com 默认不在翻墙域名列表里

**Comment by captainfrm** [comment]
翻墙成功了的。你看看我上谷歌网站的截图。
在网上找了很多办法了，依然解决不了。
哪位大神能帮忙指点一下。
前几天都可以的，就是昨天突然发现不行了。

![谷歌地图](https://github.com/ha0z1/New-Bing-Anywhere/assets/148782953/69f95199-b626-48f9-b663-770b53e71815)

**Comment by haozi** [comment]
google 能翻不代表 bing 翻成功了

**Comment by haozi** [comment]
#8
