### ISSUE TITLE
在edge上用new bing anywhere插件，依然也上不去。看看能否指点一下。CLASH用的全局，我不会设置访问bing

### ISSUE THREAD

**Issue by captainfrm** [ha0z1/New-Bing-Anywhere#271]
![依然出现国际版国内版](https://github.com/ha0z1/New-Bing-Anywhere/assets/148782953/cec644df-de49-43d0-93e2-97ac0fe45752)
![clash](https://github.com/ha0z1/New-Bing-Anywhere/assets/148782953/988f09e6-4a24-4679-8950-ae17de064a77)
 

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
翻墙没配置正确 
请先阅读 #8
