### ISSUE TITLE
无法使用聊天,一直显示达到24小时限制.

### ISSUE THREAD

**Issue by ottohalo86** [ha0z1/New-Bing-Anywhere#274]
![1698392853072](https://github.com/ha0z1/New-Bing-Anywhere/assets/104734798/e8ac0b35-231d-4577-bd2b-3794ef538b99)

奇怪的是换了个微软账号又行了,是什么bug!!!

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8
