### ISSUE TITLE
在choreme上使用该插件时一直显示重新连接

### ISSUE THREAD

**Issue by disappear0816** [ha0z1/New-Bing-Anywhere#280]
已经通过常见问题手册自查了, 
天气也显示是我梯子的地址, 比如新加坡 东京等
就是连不上, 显示页面正常, 一提问就是重新连接
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/106382036/e23468b7-48be-42ea-9cd3-f0156989ad67)

**Comment by haozi** [comment]
关掉插件呢

**Comment by eromoe** [comment]
我是一直出现验证成功，然后不断显示验证弹框，一直成功自动关闭。。

**Comment by disappear0816** [comment]
> 关掉插件呢

早上(13:00北京时间)又能用了, 不知道怎么回事, 待我继续观察, 这是在我开启插件的时候用的情况
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/106382036/3dbf0094-b4f5-4f51-8765-dedabb915837)
