### ISSUE TITLE
谷歌页面侧边栏不显示 报错

### ISSUE THREAD

**Issue by disappear0816** [ha0z1/New-Bing-Anywhere#281]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/106382036/7371cabe-f463-4891-869d-edde6c4876e7)

**Comment by haozi** [comment]
英文写得很清楚了

**Comment by disappear0816** [comment]
点击了allow没作用, 已经是最新版插件了, 去插件那里点击全部允许这个选项也是点不了的

**Comment by disappear0816** [comment]
> 点击了allow没作用, 已经是最新版插件了, 去插件那里点击全部允许这个选项也是点不了的

早上又能用了, 不知道怎么回事, 待我继续观察
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/106382036/e5720dda-deef-4a83-9b91-3b5e8cf4a8b9)

**Comment by haozi** [comment]
> > 点击了allow没作用, 已经是最新版插件了, 去插件那里点击全部允许这个选项也是点不了的
> 
> 我也是点了allow没反应，控制台不增加新的报错信息。已有的报错信息如下： ![06_44_15-1699512254010.png](https://camo.githubusercontent.com/42d6cc7ee3be295a70dd943e677d7fc3edfba0c80fb9f36e09f795e883791980/68747470733a2f2f696d672e69647a632e746f702f706963676f696d672f323032332f31312f30392f30365f34345f31352d313639393531323235343031302e706e67)

401 未授权，可能原因：
1.  bing.com 没有登录
2. google.com 没有允许带第三方 cookie 到 bing.com

**Comment by haozi** [comment]
抓下包，看看 这个请求的 Request Headers 中的 Cookie 值有没有发出去

<img width="1195" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/37101562-d636-409b-b6dd-d8cebeb8fa3d">

**Comment by disappear0816** [comment]
我排查以后发现是我梯子的问题, 换个梯子就能进newbing 和 openai官网了, 新梯子是支持进入chatgpt的 , 旧梯子可以进openai官网但是进不了chatgpt
