### ISSUE TITLE
Error: User needs to solve CAPTCHA to continue.（不断重复）

### ISSUE THREAD

**Issue by EawenZhao** [ha0z1/New-Bing-Anywhere#285]
和自查贴中的情况类似，只是在官方界面中 solve captcha 之后无法继续，会重新跳出 captcha 并不断重复。
系统 MacOS Sonoma
浏览器环境：Chrome + NewBingAnywhere

 

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-HK, zh-TW, zh, en-US, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
Your IP has been banded. You can download the mobile Edge App, log in with the same account, initiate a casual conversation, and complete the verification.

IP 被限制了，可以下个手机版 edge ，登录相同的帐号，随便发条对话，完成验证

**Comment by EawenZhao** [comment]
> Your IP has been banded. You can download the mobile Edge App, log in with the same account, initiate a casual conversation, and complete the verification.
> 
> IP 被限制了，可以下个手机版 edge ，登录相同的帐号，随便发条对话，完成验证

感谢，问题已经解决🙏

**Comment by TurnOffNOD** [comment]
> Your IP has been banded. You can download the mobile Edge App, log in with the same account, initiate a casual conversation, and complete the verification.
> 
> IP 被限制了，可以下个手机版 edge ，登录相同的帐号，随便发条对话，完成验证

那么这样的话，相同的代理，ip仍然相同，还是被限制的啊？

**Comment by families** [comment]
> > Your IP has been banded. You can download the mobile Edge App, log in with the same account, initiate a casual conversation, and complete the verification.
> > IP 被限制了，可以下个手机版 edge ，登录相同的帐号，随便发条对话，完成验证
> 
> 感谢，问题已经解决🙏

现在用这种方法失效了吗？同一账号手机能用，电脑上不管Chrome还是edge浏览器都不行，不知道是什么原因

**Comment by murainwood** [comment]
目前貌似无解

**Comment by trhy123** [comment]
在手机上使用后，无限验证的问题解决了，但只有五轮对话并且没有历史会话记录

**Comment by AQUALP3RF** [comment]
> Your IP has been banded. You can download the mobile Edge App, log in with the same account, initiate a casual conversation, and complete the verification.
> 
> IP 被限制了，可以下个手机版 edge ，使用运营商网络，登录相同的帐号，随便发条对话，完成验证

谢谢

**Comment by 3chris69** [comment]
现在手机登录也不行了

**Comment by TurnOffNOD** [comment]
这个估计不是ip问题而是本扩展的问题（当然有可能是本扩展的特定版本才有的问题），我遇到过gitlab.com的captcha被影响无法通过的情况，禁用本扩展之后就能过了。

**Comment by zhouym233** [comment]
可以尝试关闭篡改猴等其他插件。

**Comment by dddzzzccc** [comment]
我发现同样的t子，在edge中用同样的账户登录new bing发一条消息、通过验证、获得回答之后，再回到chrome就不再无限人机校验了

**Comment by WeiMeng101** [comment]
> 可以尝试关闭篡改猴等其他插件。

可以了

**Comment by TurnOffNOD** [comment]
> 可以尝试关闭篡改猴等其他插件。
篡改猴插件英文名字是啥？
