### ISSUE TITLE
Cloudfare 一直提示verify you are human

### ISSUE THREAD

**Issue by xingyeyouran** [ha0z1/New-Bing-Anywhere#286]
发送消息后，Cloudfare 一直提示verify you are human
![issue](https://github.com/ha0z1/New-Bing-Anywhere/assets/43158513/ff6704df-9ad9-4156-86ea-d394bb5fd1de)
换了很多节点、流量也走对了
![Weixin Image_20231110162206](https://github.com/ha0z1/New-Bing-Anywhere/assets/43158513/f89260f4-5406-401f-a8bd-a23b1095cf9a)

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, zh, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
see  https://github.com/ha0z1/New-Bing-Anywhere/issues/285

**Comment by xingyeyouran** [comment]
> see #285 thanks
