### ISSUE TITLE
bing新检测到非edge浏览器会不停转圈加载

### ISSUE THREAD

**Issue by Ymy214** [ha0z1/New-Bing-Anywhere#290]
首先搜索时插件的错误信息:
Error: There seem to be some errors :User needs to solve CAPTCHA to continue.
Try go to Bing [Bing-chat] and send any message to resolve CAPTCHA.
点进去bing聊天时候newbing不停正在验证,验证成功反复验证,反复失败提示账号改生日
关闭再打开插件还是没用.
edge浏览器内正常
猜测微软更新了检测机制

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/286

**Comment by Ymy214** [comment]
已解决,在edge浏览器上发一条对话,回到chrome就好使了

**Comment by TC999** [comment]
> 已解决,在edge浏览器上发一条对话,回到chrome就好使了

11月23日更新：在Edge里过人机验证失效

**Comment by haozi** [comment]
换IP并清除浏览器缓存后再试
