### ISSUE TITLE
我的还是调回国内和国际界面

### ISSUE THREAD

**Issue by zaisengguo** [ha0z1/New-Bing-Anywhere#292]
我的还是调回国内和国际界面，我是win7 ，
要不要装win10

<pre>
Version: 2.4.8 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8
