### ISSUE TITLE
Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create?bundleVersion=1.1055.9` request is accessible.

### ISSUE THREAD

**Issue by w5cschool** [ha0z1/New-Bing-Anywhere#295]
<pre>
Version: 2.4.9 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 5年签证和1年签证有什么区别
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create?bundleVersion=1.1055.9` request is accessible.
</pre>

**Comment by haozi** [comment]
#8
