### ISSUE TITLE
can you give me an idea on how best to congratulate my wife on the New Year?

### ISSUE THREAD

**Issue by vladimir5719** [ha0z1/New-Bing-Anywhere#297]
<pre>
Version: 2.4.9 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.660 YaBrowser/23.9.5.660 Yowser/2.5 Safari/537.36
Lang: ru
AcceptLangs: ru, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced","X-Forwarded-For":"123.23.12.43"}</pre>

**Comment by haozi** [comment]
Need More Info to Reopen
