### ISSUE TITLE
Ｃｈａｔ　ｂａｒ

### ISSUE THREAD

**Issue by ZhouAndrew** [ha0z1/New-Bing-Anywhere#303]
<pre>
Version: 2.4.9 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: ｆｅａｔ
stack: Error: 061+8=0x22
</pre>

**Comment by haozi** [comment]
#8
