### ISSUE TITLE
可否增加对https://web.skype.com/的支持

### ISSUE THREAD

**Issue by troilus** [ha0z1/New-Bing-Anywhere#304]
不清楚skype bing目前对用户环境的判断方式，似乎和bing网页版的原理一致，以往的x-forworded-for已经失效，想尝试下这个插件是否能用于https://web.skype.com/

**Comment by haozi** [comment]
怎么个支持？

**Comment by troilus** [comment]
我不知道插件的原理，修改插件的启用网址列表后，会不会就能对skype生效了？

**Comment by haozi** [comment]
需求描述清楚才能评估
