### ISSUE TITLE
这个扩展今天还能用么？

### ISSUE THREAD

**Issue by betterqiang** [ha0z1/New-Bing-Anywhere#313]
2023.12.08，点开进不去newbing

<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
能用

**Comment by haozi** [comment]
常见问题翻看置顶 issue
