### ISSUE TITLE
不能用呀

### ISSUE THREAD

**Issue by SkyIsWhite** [ha0z1/New-Bing-Anywhere#322]
<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Lang: zh-CN
AcceptLangs: zh-CN, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8
