### ISSUE TITLE
一直验证是否真人

### ISSUE THREAD

**Issue by bxfzzti** [ha0z1/New-Bing-Anywhere#324]
<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
看置顶帖

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/285
