### ISSUE TITLE
how do I fix the problem?

### ISSUE THREAD

**Issue by baoruikang** [ha0z1/New-Bing-Anywhere#326]
<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en, zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 枕刀歌
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub?sec_access_token=TYRwasEl7qPdLiEQL9uDWw%2F1SItSTBTlJCy4d9I4UoQqYV7aS6nes72KFM%2FxCPLes4NmdBjz8jRVyuC5KWeHQvADViqrH29NTlbKGiXT4271p2TUlC3mP2br7gDgubNBjyMjavb3mETRpKCHnOg9%2FOVKO034AUTbyp%2BOyY7kaPjjoCvASX3P9J6YAxWb4LaSKMC7F7Kp9wkR%2F7v%2Fow01t7HsIm7JRcDKy%2FG5SCDKsBJ9zYQX7y7ZI6TSfsK4q%2B7k0vfDKtV1FL6a2QzHNe3jAGKqGypfo8lXUqSlV1v97hoS0kvFtR85lq%2BzZzrY6R2Gpka2UDsBhEKf7tw4%2F4EtZ6ofkRcoovJGUGvxGKDp8zJSW5c0K%2Fx8EglSNu%2BvLibG4C6S4P01%2BrUdclMgtTGM3EUNBUb%2FkFi0XeUN9Nhkj8TvNLtYXdyDLvLbAekWZSo20DZYXZ5xDwFx7J9Gm%2BDQPSRwzHIQ0%2Bv1XBAm%2BSuzxKkVNhx3HifUO5qO00Qh3L%2Fr%2FCd04TIf4lHdHsi7d3s8j%2B0msc6%2Fw93TzKLuaZsUWIS%2BMIsx6anLv8odLbv6pso07r06VlF4sN%2FmYWqoBiNNgyNaWGXYsywRdBn8buWu1X6c3k%2BNDTT3%2FkoZMdqkZHsQCknDxjUhLTPI01KXFOtuOgOG8M9CcmIGP9Xo%2BAp0t6C08rdg1yrpOEenRRTZrK8%2FEpU%2FvHM3uBNI8EKkYUj%2Fx9pZvzzcgqpqPrZV%2FQpHl5eNRzId2RIAcaqAUnx6lQxJ4hwkTEhma203KwNh%2BsjNw3p3JuWMKuhbG%2FclytWGIYdLWPrJI9rFvGsfO8VoA%2BE9Wjqg%2FXpBYPJFEjt227CPIV85j5ce
</pre>

**Comment by haozi** [comment]
#8
