### ISSUE TITLE
耗子您好，我是中国用户，又不能使用new bing了

### ISSUE THREAD

**Issue by Vileicht** [ha0z1/New-Bing-Anywhere#327]
耗子您好，我是中国用户，又不能使用new bing了。之前一直基于你这个工具使用new bing，最近这1周左右时间又无法使用new bing了，不知道出了什么问题。

**Comment by haozi** [comment]
目前使用度正常，建议按 #8  自查。如果还是不行提供详细信息

**Comment by Vileicht** [comment]
耗子，您好！
感谢您的回复，我对程序这些比较外行，只能大致描述我目前遇到的问题。
一般情况下，每次我的电脑系统更新打补丁时，new
bing往往就用不了了，但过几天，在你更新你的New-Bing-Anywhere这个插件后，我的new bing就可以正常使用了。
但这次情况不太一样，我不记得最近有过电脑系统更新的情况，但大概在一周前，new bing不好用了。点击以后，显示如下，持续有很长时间了。关于你说的按
#8 <https://github.com/ha0z1/New-Bing-Anywhere/issues/8> 自查，我不是很懂哈。
如果方便，能否添加你的微信呢，我的微信是13466600168。我可以付费获取你的技术支持哈，非常感谢！
[image: image.png]

耗子 ***@***.***> 于2023年12月25日周一 15:37写道：

**Comment by haozi** [comment]
有 telegram 群，我的微信你想找也能找到

**Comment by Vileicht** [comment]
您好， telegram 群怎么加入哈，我不是编程人员，为了解决这个new
bing不能使用的问题，昨天才注册的Github，这些东西对于我就是天书，完全搞不清楚哪跟哪哈。
我唯一能想到的就是付费获取您或者您的团队人员的技术支持哈，在我这是很棘手的问题，可能对于你们三下五除二就能搞定的。
你看能帮我解决问题吗，我该提供哪些信息呢

耗子 ***@***.***> 于2023年12月26日周二 10:19写道：

**Comment by Vileicht** [comment]
耗子老师，谢谢哈，刚才试了下，突然就好用了，不知道咋回事

Qi Pan ***@***.***> 于2023年12月26日周二 10:24写道：

**Comment by Vileicht** [comment]
耗子老师，我以为new
bing好了呢，结果只是好了一阵，现在又不能用了，不知道是什么原因哈。非常需要您的指点哈，我该提供什么信息，你才能了解我的问题呢？

Qi Pan ***@***.***> 于2023年12月26日周二 13:47写道：

**Comment by Vileicht** [comment]
哥，帮个忙哈，我的new bing还是用不了，我实在不知道问题出在哪，也不知道该向你提供哪些信息。

Qi Pan ***@***.***> 于2023年12月26日周二 15:22写道：

**Comment by Vileicht** [comment]
哥，我问了gpt 4如下问题，他的答复如下：

你好，我是中国用户，new
bing在国内无法正常使用，因此我在edge浏览器上安装了一个叫做New-Bing-Anywhere的插件，就可以使用new
bing了。但最近一段时间，new bing又不能使用了，咨询了New-Bing-Anywhere插件的作者，他的答复如下“目前使用度正常，建议按
#8 自查。如果还是不行提供详细信息”，我看不懂，你能帮我解释下吗

"New-Bing-Anywhere"插件的作者建议您按照FAQ（常见问题自查手册）中的第8项进行自查。这个手册提供了一系列问题解决步骤和建议，包括确保使用海外IP（对中国大陆用户来说），确保某些特定域名不是直连，以及其他可能的技术步骤。如果这些步骤无法解决您的问题，建议提供更详细的信息，如浏览器版本、屏幕截图等，以便更好地诊断问题

Qi Pan ***@***.***> 于2023年12月27日周三 09:25写道：
