### ISSUE TITLE
您好，我最近无法正常使用new bing，麻烦帮我看看问题出在哪

### ISSUE THREAD

**Issue by Vileicht** [ha0z1/New-Bing-Anywhere#329]
您好，我最近无法正常使用new bing，麻烦帮我看看问题出在哪
由于我对程序一窍不通，不知道该怎么准确描述问题，也看了#8常见问题自查手册，只能截图让您帮我看看问题所在了
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/154788268/1670db72-8715-4160-a861-c6d53c743d6e)

<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
<img width="815" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/749cfa4f-f9bb-4777-89bf-335a613548c9">
<img width="988" alt="image" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/4150641/a16b98ae-2670-4685-ab4d-64b80f89f46a">

**Comment by Vileicht** [comment]
您看看，没走直连呀
[image: image.png]

耗子 ***@***.***> 于2023年12月27日周三 10:48写道：

**Comment by Vileicht** [comment]
你好，能提供个微信号吗，我付费咨询，我自己实在是搞不定new bing了

Qi Pan ***@***.***> 于2023年12月27日周三 16:46写道：

**Comment by Vileicht** [comment]
我想付费咨询哈，你给我个微信呗，在这个平台问来问去的，毫无进展呀

**Comment by haozi** [comment]
7827648

**Comment by Vileicht** [comment]
谢谢，已在微信添加您，麻烦通过下哈

耗子 ***@***.***> 于2023年12月30日周六 09:03写道：
