### ISSUE TITLE
 Failed to create session.

### ISSUE THREAD

**Issue by ZhouAndrew** [ha0z1/New-Bing-Anywhere#330]
<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 蔌
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create?bundleVersion=1.1055.9` request is accessible.
</pre>

**Comment by haozi** [comment]
try  #8   first
