### ISSUE TITLE
老师您好

### ISSUE THREAD

**Issue by Vileicht** [ha0z1/New-Bing-Anywhere#331]
我最近一直无法正常使用new bing，非常需要你的帮助，在这个平台跟你沟通了2次，效率很低，无法实质解决问题，能否提供一个私人微信，我想付费咨询并获取技术支持，方便在未来遇到问题时，可以更好的解决，非常感谢！
![1](https://github.com/ha0z1/New-Bing-Anywhere/assets/154788268/2a76d43f-412a-4a1a-933a-df084e9bc5c7)
![2](https://github.com/ha0z1/New-Bing-Anywhere/assets/154788268/adb251c0-b90e-4310-b1e5-737d5a13fb11)

**Comment by TurnOffNOD** [comment]
微信上的讨论是不公开的，无法检索，对别人遇到相同问题时候是没有帮助的。
