### ISSUE TITLE
New bing无法使用了，请提供帮助，多谢哈

### ISSUE THREAD

**Issue by Vileicht** [ha0z1/New-Bing-Anywhere#332]
最近一周，我的new bing无法正常使用，我已按照#8进行自查，经查，我使用的代理没问题，没采用直连模式，没找到问题根源。
想请你帮忙，看看能否解决我的问题，我这边可以付费获取技术支持，谢谢！

**Comment by Ely5ia** [comment]
你在代理下（试试用Proxy Switcher扩展），设置Bing的地区/国家为美国试试。

**Comment by Vileicht** [comment]
好的，明白，我试试哈

Elysia ***@***.***> 于2024年1月1日周一 11:16写道：
