### ISSUE TITLE
仍然跳转到国内版

### ISSUE THREAD

**Issue by yang11235** [ha0z1/New-Bing-Anywhere#335]
Chrome浏览器，全局模式，cookie已清理，点击插件中的newbing，仍然跳转到国内版，网址显示为：https://www.bing.com/search?q=Bing+AI&showconv=1

此外，点击copilot的情况下，会跳到登录页面，但点击登录按钮，会新开一样的登录页面窗口

<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, ja, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
#8 

copilot 登录不了是微软的 bug
