### ISSUE TITLE
直接在bing.com点击chat后报错

### ISSUE THREAD

**Issue by hhzzll** [ha0z1/New-Bing-Anywhere#340]
点击chat跳转后界面如下且无法输入
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/76993986/5042eebc-f2cd-467c-8205-2230daf1f8ee)
console报错如下
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/76993986/29e1a1d0-00d3-43ba-ae19-8b594de51ad2)
不过在bing.com先搜索后再点击chat可正常

**Comment by haozi** [comment]
微软的 bug
