### ISSUE TITLE
Coplot和New bing有啥不同

### ISSUE THREAD

**Issue by JasonxlxCharles** [ha0z1/New-Bing-Anywhere#341]
从Chrome右上角点开扩展程序之后，有两个，分别是Coplot和New bing，这两个除了名字以外还有啥不同吗？
对了，我发现Coplot只能发5条，而且没有历史记录，这是Coplot的特性吗？
谢谢了

**Comment by JasonxlxCharles** [comment]
对了，我还发现从扩展程序的渠道进入New Bing，它回答时会用中英文双语回答，而如果通过输入网址进入New Bing，就只会有中文回答，这是为什么？

**Comment by haozi** [comment]
其实没啥区别，微软已经改了几次品牌了
