### ISSUE TITLE
验证中，验证成功 死循环

### ISSUE THREAD

**Issue by BESTLyc** [ha0z1/New-Bing-Anywhere#343]
可以打开，但是对话输入后一直显示验证中，验证成功，然后继续验证中验证成功，无限循环

<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/285
