### ISSUE TITLE
SideBar 失效了

### ISSUE THREAD

**Issue by songofhawk** [ha0z1/New-Bing-Anywhere#344]
可以正常打开 Copilot 页面，网络也正常，google 可以搜索，monica 的 sidebar 也可以正常工作，但 new bing  anywhere 的 死的 sidebar 始终无法连接

<pre>
Version: 2.5.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en, zh-CN, zh, af, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: stablediffusion webui failed commit an already committed command buffer
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create?bundleVersion=1.1055.9` request is accessible.
</pre>

**Comment by haozi** [comment]
网络问题，试下在 new bing 页面是否能正常工作
