### ISSUE TITLE
在非Edge浏览器中使用Bing时没有历史记录和笔记本

### ISSUE THREAD

**Issue by Gally-Youko** [ha0z1/New-Bing-Anywhere#346]
前几天都还有历史记录的，今天打开就没了，Edge里面有。我Edge和Chrome浏览器都装的相同插件和脚本，应该不是其他插件和脚本的问题，不知哪里出问题了？
Chrome浏览器中的Bing的聊天页面 https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx
中没有，但是Copilot   https://copilot.microsoft.com/
中有
可以看下图这两个网站的不同界面：
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/138993330/d5029afd-e8f9-4eee-8aa7-b0243634efe6)
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/138993330/1ae3bb66-5f8d-42c7-be43-c75868f395d8)
希望作者查明问题，谢谢！

**Comment by haozi** [comment]
嗯，微软升级 Edge 浏览器判断逻辑了，须要升级伪装代码了，这几天会发新版

**Comment by Gally-Youko** [comment]
感谢！

**Comment by haozi** [comment]
Upgrade to 2.7.1 
and clean all bing.com's cookies

**Comment by dawn-lc** [comment]
Chrome 121.0.6167.161 
手动清空cookies 这个问题依旧存在，但是在开发者工具中修改UA后功能就正常了
![动画](https://github.com/ha0z1/New-Bing-Anywhere/assets/30336566/9f2f3dab-ed66-477f-aa7e-c69f1007ccaa)

Version: 2.7.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, ja, en, ru
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}
