### ISSUE TITLE
No "copilot"？Try enable DRF(Dangerous Request Forgery)

### ISSUE THREAD

**Issue by Tony629** [ha0z1/New-Bing-Anywhere#348]
![QQ截图20240206150800](https://github.com/ha0z1/New-Bing-Anywhere/assets/58281364/9a66510a-c81a-4436-815b-4c0c4ecfe372)

VPN没问题，可以访问谷歌，用的Clash客户端，

访问new bing anywhere, 提示 No copilot

**Comment by haozi** [comment]
不是引导你去开 DRF 么？

**Comment by Auroraee** [comment]
请问你解决了吗？

**Comment by Auroraee** [comment]
> ![QQ截图20240206150800](https://github.com/ha0z1/New-Bing-Anywhere/assets/58281364/9a66510a-c81a-4436-815b-4c0c4ecfe372)
> 
> VPN没问题，可以访问谷歌，用的Clash客户端，
> 
> 访问new bing anywhere, 提示 No copilot

请问你解决了吗？

**Comment by Tony629** [comment]
> > ![QQ截图20240206150800](https://private-user-images.githubusercontent.com/58281364/302532498-9a66510a-c81a-4436-815b-4c0c4ecfe372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTQwMzgsIm5iZiI6MTcwOTUxMzczOCwicGF0aCI6Ii81ODI4MTM2NC8zMDI1MzI0OTgtOWE2NjUxMGEtYzgxYS00NDM2LTgxNWItNGMwYzRlY2ZlMzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAwNTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODQxZDExZTRhNzVjMzhkZjI5ZjdjMWViNzZmZGYxNDMxYTU2OTVjMTkxOWVmZTBiZGZiNGRhNjU2MTE3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dlGERr8FKNSwQlLj_I9bYq9dzi23dlBbkcXIC92v-WU)
> > VPN没问题，可以访问谷歌，用的Clash客户端，
> > 访问new bing anywhere, 提示 No copilot
> 
> 请问你解决了吗？

并没有解决

**Comment by Tony629** [comment]
> 无语了。。

虽然没有解决，但是还是感谢你回复。
