### ISSUE TITLE
有历史记录和插件但单次会话还是限制5问答

### ISSUE THREAD

**Issue by banxian** [ha0z1/New-Bing-Anywhere#354]
在上次2.7.1更新后, 清除cookies再重新登陆可以刷出历史记录, 也不提示安装edge , 但左侧的单会话问答次数还是最大5次, 似乎插件/历史部分和chat问答部分有分开的风控检测.

<pre>
Version: 2.7.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN, zh, ja, zh-TW
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
帐号问题，换个帐户并清空 cookie 重登录

**Comment by surge-squirrel** [comment]
必须换号吗？

**Comment by surge-squirrel** [comment]
> 帐号问题，换个帐户并清空 cookie 重登录

没用，这个同样的号，换edge就好了
