### ISSUE TITLE
能否限制newbing页面的滚动范围? 

### ISSUE THREAD

**Issue by CCCAUCHY** [ha0z1/New-Bing-Anywhere#355]
能否限制newbing页面的滚动范围? 等待newbing时不小滚过头了, 到了oldbing, 再滚回去newbing就不响应了

<pre>
Version: 2.7.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en
config: {"showGoogleButtonOnBing":false,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
No plans to do this feature
