### ISSUE TITLE
Repeat login interface

### ISSUE THREAD

**Issue by Kuuzan** [ha0z1/New-Bing-Anywhere#356]
Hi, when I click the "copilot", there will be a repeat login interface. And when I click new bing, It will redirect to "cn.bing.com". I've tried to  clear cookies, relogin and change my area to "United States", but there was no improvement. 

![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/119334982/731c7ef3-b9ee-46dd-abd5-c8a7e5cf79bd)

<pre>
Version: 2.7.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
it's MS's bug, there's nothing I can do about it

**Comment by haozi** [comment]
Or maybe you enabled "modheader" extension
