### ISSUE TITLE
always ask for captcha

### ISSUE THREAD

**Issue by vicjeremy** [ha0z1/New-Bing-Anywhere#369]
<pre>
Version: 2.7.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: id-ID, id, en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Creative"}</pre>

**Comment by haozi** [comment]
Try this

https://github.com/ha0z1/New-Bing-Anywhere/issues/285
