### ISSUE TITLE
为啥每次进入new bing页面的时候都会自动发一遍 Bing Ai

### ISSUE THREAD

**Issue by JasonxlxCharles** [ha0z1/New-Bing-Anywhere#373]
使用那个copilot界面一直提示需要登陆，选择登陆后无效，所以用了New Bing界面。之前使用没有问题，在这几天莫名其妙的每次打开New Bing网页，都会自动发送一遍Bing Ai这两个词，不知道是这个插件的问题还是我自己的问题。不过问题不大，不怎么影响使用。

**Comment by haozi** [comment]
自己的问题，换个浏览器试试
