### ISSUE TITLE
why

### ISSUE THREAD

**Issue by yuky163** [ha0z1/New-Bing-Anywhere#374]
![image](https://github.com/ha0z1/New-Bing-Anywhere/assets/40620947/cb4e007c-89b0-4efd-ad14-5dab4215b7de)

<pre>
Version: 2.7.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/285
