### ISSUE TITLE
一直都在真人验证，验证通过马上又来

### ISSUE THREAD

**Issue by siliconvallley** [ha0z1/New-Bing-Anywhere#376]
<img width="841" alt="截屏2024-04-04 18 59 06" src="https://github.com/ha0z1/New-Bing-Anywhere/assets/18340690/c069b8d5-1d97-4e67-8be9-22bc1ffe6ae3">

<pre>
Version: 2.7.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":false,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/ha0z1/New-Bing-Anywhere/issues/285
