### ISSUE TITLE
Dose not work on Opera

### ISSUE THREAD

**Issue by jongt23** [ha0z1/New-Bing-Anywhere#58]
opera-developer June 14, 2023 the extension doesn't work

Version: 2.0.1 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/101.0.0.0 (Edition developer)
Lang: en-US
AcceptLangs: es, es-ES
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
Thank you, it will be fixed in version 2.0.3.

**Comment by haozi** [comment]
In one to two weeks, you can expect the update, or you can try [Vivaldi](https://vivaldi.com/), which was also founded by Opera creators.
