### ISSUE TITLE
Error: There seem to be some errors :WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.

### ISSUE THREAD

**Issue by zz18** [ha0z1/New-Bing-Anywhere#94]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/55685158/d42f3afa-226a-484b-bd36-2407fb1163cf)
 用的是clash，日本ip,这个咋解决呀

<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, zh-HK
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 如何正确搜索论文keywords
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
把这个域名加入列表

**Comment by zz18** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/55685158/399be76f-619c-4a0d-824d-900d3463557c)
我像这样加入貌似还是不行

**Comment by haozi** [comment]
直接bingchat 聊天呢

**Comment by zz18** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/55685158/a95a6bab-fa42-4639-955b-9303f9265c03)

**Comment by zz18** [comment]
不支持聊天。。
